// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfKk2sTWpg47f53A9HdDNHk5H2QkMsVM',
    appId: '1:383833337317:web:5b9142d05cfb393eddd30c',
    messagingSenderId: '383833337317',
    projectId: 'fastmiam',
    authDomain: 'fastmiam.firebaseapp.com',
    storageBucket: 'fastmiam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHAWW6psEJ0VG58VV0Olqg3-2mEpblks',
    appId: '1:383833337317:android:34f0b94d60ef74adddd30c',
    messagingSenderId: '383833337317',
    projectId: 'fastmiam',
    storageBucket: 'fastmiam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeGCOtvZRcB9BZv0eMVWbV8w6a_6pnFP8',
    appId: '1:383833337317:ios:4fccc3abb5f495f6ddd30c',
    messagingSenderId: '383833337317',
    projectId: 'fastmiam',
    storageBucket: 'fastmiam.appspot.com',
    iosClientId:
        '383833337317-qf3mp9tmt0e40sm2f4i43rn5k7a99k4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastmiam',
  );
}
